# All Stats
[stats]
Healthcare = 0
Employment = 0
Pollution = 0
Literacy = 0
Recreation = 0
GreenSpace = 0
PropertyValue = 0

# Actions
[actions.BuildHospital]
Healthcare = 1
Employment = 0.2
Pollution = 0.1
Literacy = 0.1

[actions.BuildPark]
Recreation = 0.8
Pollution = -0.3
GreenSpace = 0.6
PropertyValue = 0.1
