# All Stats (10)
[stats]
Population = 0       # Ideal: 0.0005
Pollution = 0        # Ideal: 0
Recreation = 0       # Ideal: 1
Employment = 0       # Ideal: 1
Literacy = 0         # Ideal: 1
Crime = 0            # Ideal: 0
HouseholdIncome = 0  # Ideal: 1
GreenSpace = 0       # Ideal: 1
Healthcare = 0       # Ideal: 1
InternetCoverage = 0 # Ideal: 1

# Actions (10)
[actions.BuildHospital]
Healthcare = 0.0003
Employment = 0.0001
Pollution = 0.0001
Literacy = 0.0001
Recreation = -0.0001
HouseholdIncome = -0.0003
GreenSpace = -0.0001
Crime = -0.0001

[actions.BuildPark]
Recreation = 0.0004
Pollution = -0.0003
GreenSpace = 0.0003
Employment = 0.0001
HouseholdIncome = 0.0001
Crime = -0.0001
Population = 0.0001
Literacy = -0.0001
InternetCoverage = -0.0001

[actions.BuildFactory]
Pollution = 0.0003
Employment = 0.0004
HouseholdIncome = 0.0002
GreenSpace = -0.0002
Crime = -0.0001
Literacy = -0.0001
Population = 0.0002
Healthcare = -0.0001

[actions.BuildTransport]
Pollution = 0.0002
Employment = 0.0003
Recreation = -0.0001
Crime = -0.0001
GreenSpace = -0.0001
HouseholdIncome = -0.0001
Literacy = -0.0001
Population = -0.0001
InternetCoverage = -0.0003

[actions.BuildEducationInstitutes]
Literacy = 0.0004
Employment = 0.0002
Population = 0.0001
Recreation = 0.0001
HouseholdIncome = -0.0001
Crime = -0.0001
Healthcare = -0.0002
Pollution = -0.0002

[actions.BuildResidentialBuilding]
Population = 0.0003
Employment = 0.0002
HouseholdIncome = 0.0001
GreenSpace = -0.0003
Crime = 0.0001
Pollution = 0.0001
Literacy = -0.0002
Healthcare = 0.0001
Recreation = 0.0002

[actions.BuildOffices]
Employment = 0.0005
HouseholdIncome = 0.0004
Literacy = 0.0001
Pollution = 0.0001
Crime = 0.0001
GreenSpace = -0.0002
Recreation = -0.0002
Healthcare = 0.0001
InternetCoverage = 0.0001

[actions.BuildTower]
InternetCoverage = 0.0005
Employment = 0.0002
Pollution = 0.0001
GreenSpace = -0.0001
Crime = 0.0001
Population = -0.0002
Healthcare = -0.0001

[actions.BuildFarm]
GreenSpace = 0.0005
Employment = -0.0001
HouseholdIncome = 0.0001
Pollution = -0.0001
Recreation = -0.0001
Healthcare = -0.0001
Population = -0.0003
Literacy = -0.0001
InternetCoverage = -0.0002

[actions.DevelopRenewableEnergy]
Pollution = -0.0003
Employment = 0.0002
HouseholdIncome = 0.0001
GreenSpace = 0.0001
Crime = -0.0001
Literacy = 0.0001
Healthcare = 0.0001
InternetCoverage = 0.0001
