# All Stats (10)
[stats]
Population = 0       # Ideal: 0.5
Pollution = 0        # Ideal: 0
Recreation = 0       # Ideal: 1
Literacy = 0         # Ideal: 1
PublicSafety = 0     # Ideal: 1
HouseholdIncome = 0  # Ideal: 1
GreenSpace = 0       # Ideal: 1
Healthcare = 0       # Ideal: 1
Employment = 0       # Ideal: 1
InternetCoverage = 0 # Ideal: 1

# Actions (10)
[actions.BuildHospital]
Healthcare = 0.8
Employment = 0.2
Pollution = 0.2
Literacy = 0.1
Recreation = 0.1

[actions.BuildPark]
Recreation = 0.8
Pollution = -0.5
GreenSpace = 0.6
Employment = 0.1
HouseholdIncome = 0.1

[actions.BuildFactory]
Pollution = 0.8
Employment = 0.7
HouseholdIncome = 0.5
GreenSpace = -0.4
PublicSafety = -0.3

[actions.BuildTransport]
Pollution = 0.5
Employment = 0.6
Recreation = -0.3
PublicSafety = -0.1

[actions.BuildEducationInstitutes]
Literacy = 0.7
Employment = 0.3
Population = 0.3
Recreation = 0.1

[actions.BuildResidentialBuilding]
Population = 0.6
Employment = 0.4
HouseholdIncome = 0.3
GreenSpace = -0.2
PublicSafety = 0.2

[actions.BuildOffices]
Employment = 0.8
HouseholdIncome = 0.7
Literacy = 0.1
Pollution = 0.1

[actions.DevelopScienceCenter]
Literacy = 0.8
Employment = 0.5
Pollution = 0.2
Recreation = 0.2

[actions.BuildFarm]
GreenSpace = 0.8
Employment = -0.4
HouseholdIncome = 0.2
Pollution = -0.4

[actions.DevelopRenewableEnergy]
Pollution = -0.6
Employment = 0.5
HouseholdIncome = 0.2
GreenSpace = 0.2
